spring.application.name=Ai-chatbot-bakend

spring.ai.openai.api-key=${API_KEY}
spring.ai.openai.chat.options.model=${API_MODEL}
spring.ai.openai.base-url=${API_URL}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.ai.chat.memory.repository.jdbc.initialize-schema=always